
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Add_Movie.java
 *
 * Created on Jul 23, 2014, 4:38:23 PM
 */

/**
 *
 * @author sd
 */
public class Add_Movie extends javax.swing.JFrame {

    /** Creates new form Add_Movie */
    public Add_Movie() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Add new movie to the list !");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 310, 39);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Movie_Code  :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 110, 87, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Name             :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 140, 100, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Sequel           :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 170, 89, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Director         :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 200, 89, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Publisher        :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 230, 92, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Duration         :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 260, 94, 15);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 110, 130, 20);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 140, 130, 20);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(220, 170, 130, 20);

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(220, 200, 130, 20);

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(220, 230, 130, 20);

        jTextField7.setToolTipText("Enter duration in the form hh:mm(e.g.02:35)");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(220, 260, 130, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-edit-add-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 220, 120, 110);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/untitled.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 190, 110, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesEL8DZX3C.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(560, 240, 60, 70);

        jLabel2.setText("BACK");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(580, 310, 34, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/depositphotos_9006605-Colorful-film-strip.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-100, 0, 780, 400);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-670)/2, (screenSize.height-387)/2, 670, 387);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String mov_code=jTextField2.getText();
String name=jTextField3.getText();
String sequel=jTextField4.getText();
String director=jTextField5.getText();
String publisher=jTextField6.getText();
String duration=jTextField7.getText();

if(mov_code.isEmpty()||name.isEmpty()||sequel.isEmpty()||director.isEmpty()||publisher.isEmpty()||duration.isEmpty())
{
    JOptionPane.showMessageDialog(null,"please enter required information");    
}
else
{
try
         {
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection
                   ("jdbc:mysql://localhost/theatre_management_system","root","");
           Statement stmt=con.createStatement();
             
              String mc=jTextField2.getText();
              String nm=jTextField3.getText();
              String sql=jTextField4.getText();
              String dir=jTextField5.getText();
              String pub=jTextField6.getText();
              String dur=jTextField7.getText();


           String q="insert into movie values("+(mc)+"','"+(name)+"','"+
                   (sequel)+"','"+(dir)+"','"+(pub)+"','"+(dur)+"');";
           stmt.executeUpdate(q);
           JOptionPane.showMessageDialog(this, "Record Inserted!");      
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
       
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this, e.getMessage());
       }        
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Admin_resources().setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed

    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
char kc=evt.getKeyChar();
     if(!((kc>='0' && kc<='9') || kc==KeyEvent.VK_BACK_SPACE || kc==KeyEvent.VK_DELETE||kc==KeyEvent.VK_COLON))
     {
         JOptionPane.showMessageDialog(this, "Enter duration in the form hh:mm(e.g.02:35)!");
         evt.consume();
       
     }       
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
      char kc=evt.getKeyChar();
     if(((kc>='0' && kc<='9') || kc==KeyEvent.VK_BACK_SPACE || kc==KeyEvent.VK_DELETE))
     {
         JOptionPane.showMessageDialog(this, "Please enter text only");
         evt.consume();
         jTextField7.setText("");
     }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
       char kc=evt.getKeyChar();
     if(!((kc>='0' && kc<='9') || kc==KeyEvent.VK_BACK_SPACE || kc==KeyEvent.VK_DELETE))
     {
         JOptionPane.showMessageDialog(this, "Please enter only numeric values");
         evt.consume();
         jTextField7.setText("");
     }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
      char kc=evt.getKeyChar();
     if(((kc>='0' && kc<='9') || kc==KeyEvent.VK_BACK_SPACE || kc==KeyEvent.VK_DELETE))
     {
         JOptionPane.showMessageDialog(this, "Please enter text only");
         evt.consume();
         jTextField7.setText("");
     }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
      char kc=evt.getKeyChar();
     if(((kc>='0' && kc<='9') || kc==KeyEvent.VK_BACK_SPACE || kc==KeyEvent.VK_DELETE))
     {
         JOptionPane.showMessageDialog(this, "Please enter text only");
         evt.consume();
         jTextField7.setText("");
     }
    }//GEN-LAST:event_jTextField6KeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Movie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
