/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login_Administrator.java
 *
 * Created on Jul 10, 2014, 7:07:26 PM
 */

/**
 *
 * @author sd
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Login_Administrator extends javax.swing.JFrame {

    /** Creates new form Login_Administrator */
    public Login_Administrator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 240, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 280, 76, 17);

        jLabel4.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jLabel4.setText("Hello ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 70, 60, 39);

        jLabel5.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        jLabel5.setText("Please enter the details to access your account");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 150, 395, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 240, 160, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 420, 80, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 420, 90, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(70, 360, 110, 90);

        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(290, 280, 160, 20);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 190, 250, 0);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, -20, 0, 200);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 20, 390, 130);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGIN.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 190, 224, 210);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-646)/2, (screenSize.height-508)/2, 646, 508);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String admin_name=jTextField1.getText();
        String password=jPasswordField1.getText();
        try{
        Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost/theatre_management_system","root", "");
 Statement stmt = con.createStatement();
 String existingUserQuery = "Select * from  Admin_info where admin_name='" 
         + admin_name + "'&& password='" + password + "';";
                ResultSet rs = stmt.executeQuery(existingUserQuery);
                if (rs != null && rs.next()) {
                  JOptionPane.showMessageDialog(this, "Successfully Logged In");
                    new Admin_resources().setVisible(true);
                  this.setVisible(false);
                } else if (rs == null || rs.next() == false) {
                    JOptionPane.showMessageDialog(this, "wrong Username or Password!");
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                }
            }
      catch (Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         new Homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
     jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
