
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Movie_list_Admin.java
 *
 * Created on Jul 25, 2014, 2:04:14 PM
 */

/**
 *
 * @author sd
 */
public class Movie_list_Admin extends javax.swing.JFrame {

    /** Creates new form Movie_list_Admin */
    public Movie_list_Admin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 70, 29, 15);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Action", "Love Story", "Adventure", "Horror", "Animated", "Comedy" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 100, 70, 130);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S_No", "Movie_Code", "Name", "Sequel", "Director", "Publisher", "Duration"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 70, 570, 160);

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALL MOVIES IN THE THEATRE ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 330, 39);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 250, 80, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(620, 250, 80, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12927553-Dark-blue-technology-background-Stock-Photo-technical.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-460, 0, 1220, 310);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-758)/2, (screenSize.height-323)/2, 758, 323);
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String table=(String)jList1.getSelectedValue();

        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();

        if(jList1.getSelectedIndex()==0) {
            try {
                int rows=model.getRowCount();
                if(rows>0) {
                    for(int i=0;i<rows;i++) {
                        model.removeRow(0);
                    }
                }
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection
                        ("jdbc:mysql://localhost/Theatre_Management_System","root","");
                Statement stmt=con.createStatement();
                String Tno= (String)jList1.getSelectedValue();
                String q1="select * from movie where movie_code like 'ac%';";
                ResultSet rs=stmt.executeQuery(q1);
                while(rs.next()) {
                    String sno=rs.getString("S_no");
                    String mc=rs.getString("Movie_Code");
                    String name=rs.getString("Name");
                    String sequel=rs.getString("Sequel");
                    String direc=rs.getString("Director");
                    String pub=rs.getString("Publisher");
                    String durat=rs.getString("Duration");
                    model.addRow(new Object[]{sno,mc,name,sequel,direc,pub,durat});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        else if(jList1.getSelectedIndex()==1) {
            try {
                int rows=model.getRowCount();
                if(rows>0) {
                    for(int i=0;i<rows;i++) {
                        model.removeRow(0);
                    }
                }
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection
                        ("jdbc:mysql://localhost/Theatre_Management_System","root","");
                Statement stmt=con.createStatement();
                String Tno= (String)jList1.getSelectedValue();
                String q1="select * from movie where movie_code like 'ls%';";
                ResultSet rs=stmt.executeQuery(q1);
                while(rs.next()) {
                    String sno=rs.getString("S_no");
                    String mc=rs.getString("Movie_Code");
                    String name=rs.getString("Name");
                    String sequel=rs.getString("Sequel");
                    String direc=rs.getString("Director");
                    String pub=rs.getString("Publisher");
                    String durat=rs.getString("Duration");
                    model.addRow(new Object[]{sno,mc,name,sequel,direc,pub,durat});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        else if(jList1.getSelectedIndex()==2) {
            try {
                int rows=model.getRowCount();
                if(rows>0) {
                    for(int i=0;i<rows;i++) {
                        model.removeRow(0);
                    }
                }
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection
                        ("jdbc:mysql://localhost/Theatre_Management_System","root","");
                Statement stmt=con.createStatement();
                String Tno= (String)jList1.getSelectedValue();
                String q1="select * from movie where movie_code like 'ad%';";
                ResultSet rs=stmt.executeQuery(q1);
                while(rs.next()) {
                    String sno=rs.getString("S_no");
                    String mc=rs.getString("Movie_Code");
                    String name=rs.getString("Name");
                    String sequel=rs.getString("Sequel");
                    String direc=rs.getString("Director");
                    String pub=rs.getString("Publisher");
                    String durat=rs.getString("Duration");
                    model.addRow(new Object[]{sno,mc,name,sequel,direc,pub,durat});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        else if(jList1.getSelectedIndex()==3) {
            try {
                int rows=model.getRowCount();
                if(rows>0) {
                    for(int i=0;i<rows;i++) {
                        model.removeRow(0);
                    }
                }
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection
                        ("jdbc:mysql://localhost/Theatre_Management_System","root","");
                Statement stmt=con.createStatement();
                String Tno= (String)jList1.getSelectedValue();
                String q1="select * from movie where movie_code like 'h%';";
                ResultSet rs=stmt.executeQuery(q1);
                while(rs.next()) {
                    String sno=rs.getString("S_no");
                    String mc=rs.getString("Movie_Code");
                    String name=rs.getString("Name");
                    String sequel=rs.getString("Sequel");
                    String direc=rs.getString("Director");
                    String pub=rs.getString("Publisher");
                    String durat=rs.getString("Duration");
                    model.addRow(new Object[]{sno,mc,name,sequel,direc,pub,durat});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        else if(jList1.getSelectedIndex()==4) {
            try {
                int rows=model.getRowCount();
                if(rows>0) {
                    for(int i=0;i<rows;i++) {
                        model.removeRow(0);
                    }
                }
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection
                        ("jdbc:mysql://localhost/Theatre_Management_System","root","");
                Statement stmt=con.createStatement();
                String Tno= (String)jList1.getSelectedValue();
                String q1="select * from movie where movie_code like 'an%';";
                ResultSet rs=stmt.executeQuery(q1);
                while(rs.next()) {
                    String sno=rs.getString("S_no");
                    String mc=rs.getString("Movie_Code");
                    String name=rs.getString("Name");
                    String sequel=rs.getString("Sequel");
                    String direc=rs.getString("Director");
                    String pub=rs.getString("Publisher");
                    String durat=rs.getString("Duration");
                    model.addRow(new Object[]{sno,mc,name,sequel,direc,pub,durat});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        else if(jList1.getSelectedIndex()==5) {
            try {
                int rows=model.getRowCount();
                if(rows>0) {
                    for(int i=0;i<rows;i++) {
                        model.removeRow(0);
                    }
                }
                Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection
                        ("jdbc:mysql://localhost/Theatre_Management_System","root","");
                Statement stmt=con.createStatement();
                String Tno= (String)jList1.getSelectedValue();
                String q1="select * from movie where movie_code like 'c%';";
                ResultSet rs=stmt.executeQuery(q1);
                while(rs.next()) {
                    String sno=rs.getString("S_no");
                    String mc=rs.getString("Movie_Code");
                    String name=rs.getString("Name");
                    String sequel=rs.getString("Sequel");
                    String direc=rs.getString("Director");
                    String pub=rs.getString("Publisher");
                    String durat=rs.getString("Duration");
                    model.addRow(new Object[]{sno,mc,name,sequel,direc,pub,durat});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
}//GEN-LAST:event_jList1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int rows= model.getRowCount();
        if(rows>0) {
            for(int i=0;i<rows;i++) {
                model.removeRow(0);
            }
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Admin_resources().setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movie_list_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
