
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * User_Profile.java
 *
 * Created on Jul 11, 2014, 9:24:18 AM
 */

/**
 *
 * @author sd
 */
public class User_Profile extends javax.swing.JFrame {

    /** Creates new form User_Profile */
    public User_Profile() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 70, 39, 15);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 180, 0, 0);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 41, 15);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 0, 2, 0);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(421, 300, 80, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email ID       :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 190, 81, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("DOB             :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 220, 82, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Password     :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 250, 83, 15);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 110, 100, 20);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(350, 190, 130, 20);

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(350, 220, 130, 20);

        jTextField6.setEditable(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(350, 250, 130, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Edit Profile");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 70, 110, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Submit");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(337, 70, 90, 23);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Clear");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(433, 70, 80, 23);

        jLabel9.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        jLabel9.setText("Welcome User!");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 20, 250, 39);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Gender       :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 130, 75, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Phone No    :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 160, 79, 15);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    ", "Male", "Female" }));
        jComboBox1.setEnabled(false);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(350, 130, 130, 20);

        jTextField3.setEditable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(350, 160, 130, 20);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Show Profile");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(31, 140, 140, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jurassic-world-park.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 900, 620);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-707)/2, (screenSize.height-562)/2, 707, 562);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         new User_resources().setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton3.setEnabled(false);
        jComboBox1.setEnabled(true);
        jTextField3.setEditable(true);
        jTextField2.setEditable(true);
        jTextField5.setEditable(true);
        jTextField6.setEditable(true);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jComboBox1.setSelectedIndex(0);
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection
                    ("jdbc:mysql://localhost/theatre_management_system","root","");
            Statement stmt=con.createStatement();
            String name=jTextField1.getText();
            String email=jTextField2.getText();
            String dob=jTextField5.getText();
            String password=jTextField6.getText();
            String q1="update user_info set email_id='"+(email)+"',dob='"+(dob)+"'" +
                    ",password='"+(password)+"' where username='"+(name)+"';";
            stmt.executeUpdate(q1);
          JOptionPane.showMessageDialog(this, "Account successfully changed!");
 jButton3.setEnabled(true);
 jButton4.setEnabled(false);
 jTextField3.setEditable(false);
        jTextField2.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);

        }
        catch(Exception e)
        {

        JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

}//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String Name=jTextField1.getText();
               try
            {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)
                        DriverManager.getConnection("jdbc:mysql://localhost:3306/theatre_management_system","root","");
                Statement stmt=(Statement)con.createStatement();
                String q1="Select password,phone_no,gender,email_id,dob from user_info where username='"+Name+"';";
                ResultSet rs=stmt.executeQuery(q1);
                if(rs.next()){
                    String password=rs.getString("password");
                    String phone_no=rs.getString("phone_no");
                    String gender=rs.getString("gender");
                    String email_id=rs.getString("email_id");
                    String dob=rs.getString("dob");
                    jTextField3.setText(phone_no);
                    jTextField2.setText(email_id);
                    jTextField5.setText(dob);
                    jTextField6.setText(password);
                    jTextField1.setEditable(false);
                    jButton6.setEnabled(false);
                    jButton3.setEnabled(true);
                    if(gender.matches("Male")){
                    jComboBox1.setSelectedIndex(1);}
                    else{jComboBox1.setSelectedIndex(2);}}}
                    catch (Exception e){
                                JOptionPane.showMessageDialog(this, e.getMessage());
                    }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
